# Global variables don't seem to work
parameters:
  CRAN: 'https://cloud.r-project.org'

jobs:
- job: Linux
  pool:
    vmImage: 'Ubuntu-16.04'
  container: cran/debian:latest
  steps:
    - template: templates/stage-all.yml
  variables:
    TZ: UTC
    BINEXT: _R_x86_64-pc-linux-gnu.tar.gz
    R_LIBS_USER: '$(Agent.BuildDirectory)/r-library'
    CHECK_ARGS: '--no-manual'
    CRAN: ${{parameters.CRAN}}

- job: Windows
  dependsOn: Linux
  condition: succeededOrFailed()
  pool:
    vmImage: 'vs2017-win2016'
  steps:
    - template: templates/r-setup-windows.yml
    - template: templates/stage-all.yml
  variables:
    BINEXT: .zip
    R_LIBS_USER: '$(Agent.WorkFolder)\r-library'
    CHECK_ARGS: '--no-manual --no-build-vignettes'
    CRAN: ${{parameters.CRAN}}

- job: macOS
  dependsOn: Linux
  condition: succeededOrFailed()
  pool:
    vmImage: macOS-10.13
  steps:
    - template: templates/r-setup-macos.yml
    - template: templates/stage-all.yml
  variables:
    BINEXT: .tgz
    R_LIBS_USER: '$(Agent.WorkFolder)/r-library'
    CHECK_ARGS: '--no-manual --no-build-vignettes'
    CRAN: ${{parameters.CRAN}}
