# Global variables don't seem to work
parameters:
  CRAN: 'https://cloud.r-project.org'

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-latest'
  container: ropensci/rspm:latest
  steps:
    - template: templates/stage-all.yml
  variables:
    TZ: UTC
    DEPLOYTYPE: src
    BINEXT: _R_x86_64-pc-linux-gnu.tar.gz
    R_LIBS_USER: '$(Agent.BuildDirectory)/r-library'
    CHECK_ARGS: '--no-manual'

- job: Windows
  dependsOn: Linux
  condition: succeededOrFailed()
  pool:
    vmImage: 'windows-latest'
  steps:
    - template: templates/r-setup-windows.yml
    - template: templates/stage-all.yml
  variables:
    BINEXT: .zip
    DEPLOYTYPE: win
    R_LIBS_USER: '$(Agent.WorkFolder)\r-library'
    CHECK_ARGS: '--no-manual --no-build-vignettes'
    CRAN: ${{parameters.CRAN}}

- job: macOS
  dependsOn: Linux
  condition: succeededOrFailed()
  pool:
    vmImage: macOS-latest
  steps:
    - template: templates/r-setup-macos.yml
    - template: templates/stage-all.yml
  variables:
    BINEXT: .tgz
    DEPLOYTYPE: mac
    R_LIBS_USER: '$(Agent.WorkFolder)/r-library'
    CHECK_ARGS: '--no-manual --no-build-vignettes'
    CRAN: ${{parameters.CRAN}}
    PKG_CONFIG_PATH: /opt/X11/lib/pkgconfig
