jobs:
- job: macOS
  pool:
    vmImage: xcode9-macos10.13
  steps:
    - template: templates/setup-osx.yml
    - template: templates/build.yml
    - script: autobrew --check src/*.tar.gz

- job: Linux
  pool:
    vmImage: ubuntu-16.04
  steps:
    - template: templates/setup-ubuntu.yml
    - template: templates/build.yml      

- job: Windows
  pool:
    vmImage: vs2015-win2012r2     
  steps:
    - template: templates/setup-windows.yml
    - template: templates/build.yml
